import { type Claim, type KnowledgeBase, type KnowledgeSource } from "./knowledge";

// Original summaries of official rulebooks and announcements, reviewed 2026-10-01. Effective-until dates are exclusive.
type Draft = Pick<Claim, "_id" | "sourceId" | "predicate" | "value" | "statement" | "aliases"> & Partial<Pick<Claim, "effectiveFrom" | "effectiveUntil" | "conditions" | "relations">>;
const claimsFor = (knowledgeBaseId: string, subject: string) => (draft: Draft): Claim => ({ knowledgeBaseId, subject, exclusive: true, version: null, effectiveFrom: null, effectiveUntil: null, conditions: [], relations: [], ...draft });
const reviewed = "2026-10-01";

export const footballBaseId = "tg-kb-football-laws";
export const footballKnowledgeBase: KnowledgeBase = {
  _id: footballBaseId,
  title: "Football rules desk",
  description: "Original summaries of the IFAB Laws of the Game for eleven-a-side football (not futsal or beach soccer) and IFAB decisions. Each rule records the season it took effect, the rule it replaced, and the kind of match or competition it applies to, so the answer matches the match you are asking about.",
  kind: "real",
  mcpId: null,
  suggestedQuestions: [
    "What happens if a goalkeeper holds the ball too long?",
    "How many substitutes can be used in an international friendly?",
    "What happens if a throw-in takes too long?",
    "What happens if a substituted player takes too long to leave the field?",
    "Can a player be sent off for walking off in protest at the World Cup 2026?",
    "What colour must the referee wear?",
  ],
  showcase: [
    { title: "Rule replaced", question: "What happens if a goalkeeper holds the ball too long?", asOf: null, lesson: "Since 1 July 2025 the limit is eight seconds and the penalty is a corner kick. A keyword search can still surface the old six-second indirect free kick; TruthGraph follows the recorded replacement." },
    { title: "Match date matters", question: "What happens if a goalkeeper holds the ball too long?", asOf: "2025-03-01", lesson: "Same question, match played on 1 March 2025: the old Law applied, so more than six seconds meant an indirect free kick. The match date decides the answer, not the newest document." },
    { title: "Depends on the match", question: "How many substitutes can a team use?", asOf: null, lesson: "Competition matches, international friendlies, and club friendlies have different limits. TruthGraph asks which kind of match instead of picking one. Add \"in an international friendly\" to get the answer." },
    { title: "Competition option", question: "Can a player get a red card for covering their mouth?", asOf: null, lesson: "In April 2026 the IFAB made this a competition option, adopted for the FIFA World Cup 2026. Answering yes for every match would be wrong, so TruthGraph asks which competition." },
    { title: "Brand-new Law", question: "A defender denies a clear goal chance, the referee plays advantage and the goal is scored. Is the defender booked?", asOf: null, lesson: "From 1 July 2026 there is no caution when the advantage leads to a goal. Last season's rule still booked the defender, so an older summary gives the wrong answer." },
  ],
};

const ifab = { knowledgeBaseId: footballBaseId, publisher: "The International Football Association Board (IFAB)", authority: "primary" as const, reviewedAt: reviewed };
export const footballSources: KnowledgeSource[] = [
  { ...ifab, _id: "tg-source-fb-ifab-2025", title: "The IFAB tackles time-wasting by goalkeepers", url: "https://www.theifab.com/news/the-ifab-tackles-goalkeeper-time-wasting/", publishedAt: "2025-03-01" },
  { ...ifab, _id: "tg-source-fb-ifab-2026-agm", title: "The IFAB introduces further measures to improve match flow and player behaviour", url: "https://www.theifab.com/news/the-ifab-introduces-further-measures-to-improve-match-flow-and-player-behaviour/", publishedAt: "2026-02-28" },
  { ...ifab, _id: "tg-source-fb-ifab-2026-special", title: "The IFAB unanimously approves red card for players covering their mouths to conceal discriminatory behaviour", url: "https://www.theifab.com/news/the-ifab-unanimously-approves-red-card-for-players-covering-their-mouths-to-conce/", publishedAt: "2026-04-29" },
  { ...ifab, _id: "tg-source-fb-law3", title: "Laws of the Game 2026/27 – Law 3: The Players", url: "https://www.theifab.com/laws/latest/the-players/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law12", title: "Laws of the Game 2026/27 – Law 12: Fouls and Misconduct", url: "https://www.theifab.com/laws/latest/fouls-and-misconduct/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law7", title: "Laws of the Game 2026/27 – Law 7: The Duration of the Match", url: "https://www.theifab.com/laws/latest/the-duration-of-the-match/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law11", title: "Laws of the Game 2026/27 – Law 11: Offside", url: "https://www.theifab.com/laws/latest/offside/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law1", title: "Laws of the Game – Law 1: The Field of Play", url: "https://www.theifab.com/laws/latest/the-field-of-play/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law8", title: "Laws of the Game – Law 8: The Start and Restart of Play", url: "https://www.theifab.com/laws/latest/the-start-and-restart-of-play/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law10", title: "Laws of the Game – Law 10: Determining the Outcome of a Match", url: "https://www.theifab.com/laws/latest/determining-the-outcome-of-a-match/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law13", title: "Laws of the Game – Law 13: Free Kicks", url: "https://www.theifab.com/laws/latest/free-kicks/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law14", title: "Laws of the Game – Law 14: The Penalty Kick", url: "https://www.theifab.com/laws/latest/the-penalty-kick/", publishedAt: null },
  { ...ifab, _id: "tg-source-fb-law15", title: "Laws of the Game – Law 15: The Throw-in", url: "https://www.theifab.com/laws/latest/the-throw-in/", publishedAt: null },
];

const football = claimsFor(footballBaseId, "Laws of the Game");
const keeperAliases = ["goalkeeper", "keeper", "goalie", "holds the ball", "holding the ball", "hold the ball", "too long", "six seconds", "eight seconds", "time-wasting"];
const substituteAliases = ["substitutes", "subs", "substitutions", "how many substitutes", "replacements"];
const matchType = (value: string) => [{ key: "match type", value }];
const worldCup = [{ key: "competition", value: "World Cup 2026" }];
const dogsoAliases = ["advantage", "clear goal chance", "obvious goal-scoring opportunity", "goal-scoring opportunity", "booked", "yellow card", "cautioned", "dogso"];
export const footballClaims: Claim[] = [
  football({ _id: "tg-claim-fb-keeper-six", sourceId: "tg-source-fb-ifab-2025", predicate: "goalkeeper holding the ball too long", value: "indirect free kick after more than six seconds", statement: "Under the Laws of the Game in force before 1 July 2025, a goalkeeper who held the ball in the hands for more than six seconds was penalised with an indirect free kick to the opponents.", aliases: keeperAliases, effectiveUntil: "2025-07-01" }),
  football({ _id: "tg-claim-fb-keeper-eight", sourceId: "tg-source-fb-ifab-2025", predicate: "goalkeeper holding the ball too long", value: "corner kick after more than eight seconds", statement: "Since the 2025/26 Laws of the Game took effect on 1 July 2025, a goalkeeper who controls the ball with the hands inside the penalty area for more than eight seconds concedes a corner kick. The referee counts down the last five seconds with a raised hand. Competitions that started before 1 July 2025, such as the FIFA Club World Cup from 14 June 2025, could apply it earlier.", aliases: keeperAliases, effectiveFrom: "2025-07-01", relations: [{ kind: "supersedes", targetId: "tg-claim-fb-keeper-six", reason: "The IFAB amended Law 12 for 2025/26, replacing the six-second indirect free kick with an eight-second limit sanctioned by a corner kick." }] }),
  football({ _id: "tg-claim-fb-throw-in-countdown", sourceId: "tg-source-fb-ifab-2026-agm", predicate: "delayed throw-in", value: "throw-in given to the opponents after a five-second countdown", statement: "Under the 2026/27 Laws of the Game (in force 1 July 2026 and approved in February 2026 for the FIFA World Cup 2026), if the referee considers a throw-in is taking too long or being deliberately delayed, a visible five-second countdown starts; if the ball is not in play when it ends, the throw-in goes to the opposing team.", aliases: ["throw-in", "throw in", "delayed throw-in", "takes too long", "countdown"], effectiveFrom: "2026-07-01" }),
  football({ _id: "tg-claim-fb-goal-kick-countdown", sourceId: "tg-source-fb-ifab-2026-agm", predicate: "delayed goal kick", value: "corner kick to the opponents after a five-second countdown", statement: "Under the 2026/27 Laws of the Game (in force 1 July 2026), a goal kick that the referee considers too slow or deliberately delayed triggers a five-second visual countdown; if the ball is not in play when it ends, the opponents are awarded a corner kick.", aliases: ["goal kick", "goal-kick", "delayed goal kick", "countdown"], effectiveFrom: "2026-07-01" }),
  football({ _id: "tg-claim-fb-substitution-ten-seconds", sourceId: "tg-source-fb-law3", predicate: "substituted player slow to leave the field", value: "the substitute waits until the first stoppage after one minute", statement: "Under the 2026/27 Laws of the Game (in force 1 July 2026), a player being substituted must be off the field within ten seconds of the substitution board, or the referee's signal. If not, the player must still leave, but the substitute may only enter at the first stoppage after one minute of play has passed since the restart.", aliases: ["substitution", "substituted", "substituted player", "leave the field", "ten seconds", "substitution board"], effectiveFrom: "2026-07-01" }),
  football({ _id: "tg-claim-fb-subs-competition", sourceId: "tg-source-fb-law3", predicate: "maximum substitutes a team may use", value: "up to five, as set by the competition", statement: "In official competition matches, FIFA, the confederation, or the national association sets how many substitutes may be used, up to five. Where five are allowed for top-division club or senior international teams, each team has at most three substitution opportunities, plus half-time.", aliases: substituteAliases, conditions: matchType("competition match") }),
  football({ _id: "tg-claim-fb-subs-international-friendly", sourceId: "tg-source-fb-law3", predicate: "maximum substitutes a team may use", value: "eight, or up to eleven if both teams agree", statement: "Since the 2026/27 Laws of the Game (1 July 2026), senior 'A' international friendlies allow up to fifteen named substitutes, of whom eight may be used; if both teams agree and tell the referee before the match, up to eleven may be used.", aliases: substituteAliases, conditions: matchType("international friendly"), effectiveFrom: "2026-07-01" }),
  football({ _id: "tg-claim-fb-subs-club-friendly", sourceId: "tg-source-fb-law3", predicate: "maximum substitutes a team may use", value: "an agreed number, otherwise six", statement: "In other matches, such as club friendlies, teams may use more substitutes if they agree a maximum and inform the referee before the match; without that agreement each team may use at most six.", aliases: substituteAliases, conditions: matchType("club friendly") }),
  football({ _id: "tg-claim-fb-mouth-cover", sourceId: "tg-source-fb-ifab-2026-special", predicate: "covering the mouth when confronting an opponent", value: "red card", statement: "At the FIFA World Cup 2026, a player who covers their mouth in a confrontation with an opponent may be sent off with a red card. The IFAB approved this on 29 April 2026 as a competition option, so it applies only where the competition organiser adopts it.", aliases: ["covering their mouth", "covering the mouth", "covers their mouth", "cover their mouth", "mouth"], conditions: worldCup, effectiveFrom: "2026-04-29" }),
  football({ _id: "tg-claim-fb-protest-walk-off", sourceId: "tg-source-fb-ifab-2026-special", predicate: "leaving the field in protest", value: "red card, and the team that causes an abandonment in principle forfeits", statement: "At the FIFA World Cup 2026, the referee may send off a player who leaves the field in protest at a decision, and any team official who incites it; a team that causes the match to be abandoned in principle forfeits. The IFAB approved this on 29 April 2026 as a competition option.", aliases: ["walking off", "walk off", "walk-off", "protest", "leaves the field in protest", "leave the field in protest"], conditions: worldCup, effectiveFrom: "2026-04-29" }),
  football({ _id: "tg-claim-fb-dogso-advantage-old", sourceId: "tg-source-fb-ifab-2026-agm", predicate: "caution after advantage when a goal chance was denied", value: "cautioned even if a goal was scored", statement: "Before the 2026/27 Laws of the Game, when the referee played advantage after an offence that denied an obvious goal-scoring opportunity, the offender was still cautioned at the next stoppage, even if the attacking team scored.", aliases: dogsoAliases, effectiveUntil: "2026-07-01" }),
  football({ _id: "tg-claim-fb-dogso-advantage-new", sourceId: "tg-source-fb-law12", predicate: "caution after advantage when a goal chance was denied", value: "no caution if the goal is scored", statement: "Since the 2026/27 Laws of the Game (1 July 2026), if the referee plays advantage after an offence that denied an obvious goal-scoring opportunity and the attacking team scores as a result, the offender receives no caution, because the offence did not prevent a goal.", aliases: dogsoAliases, effectiveFrom: "2026-07-01", relations: [{ kind: "supersedes", targetId: "tg-claim-fb-dogso-advantage-old", reason: "The IFAB's 2026/27 amendment to Law 12 removed the caution when advantage results in a goal." }] }),
  football({ _id: "tg-claim-fb-players", sourceId: "tg-source-fb-law3", predicate: "number of players per team", value: "up to eleven, at least seven", statement: "A match is played by two teams of at most eleven players each, one of whom must be the goalkeeper. A match may not start or continue if either team has fewer than seven players.", aliases: ["how many players", "players", "eleven", "team size", "fewer than seven", "minimum players"] }),
  football({ _id: "tg-claim-fb-offside", sourceId: "tg-source-fb-law11", predicate: "offside", value: "penalised only when involved in active play from an offside position", statement: "Being in an offside position is not itself an offence. A player is in an offside position when any part of the head, body, or feet is in the opponents' half and nearer to the opponents' goal line than both the ball and the second-last opponent; hands and arms do not count, and being level is onside. The player is penalised, with an indirect free kick, only on becoming involved in active play when a team-mate plays or touches the ball.", aliases: ["offside", "off side", "offside position", "second-last opponent", "onside"] }),
  football({ _id: "tg-claim-fb-offside-restarts", sourceId: "tg-source-fb-law11", predicate: "offside from a goal kick, throw-in, or corner kick", value: "no offside offence", statement: "There is no offside offence if a player receives the ball directly from a goal kick, a throw-in, or a corner kick.", aliases: ["offside", "throw-in", "throw in", "corner kick", "goal kick", "directly from"] }),
  football({ _id: "tg-claim-fb-duration", sourceId: "tg-source-fb-law7", predicate: "length of a match", value: "two halves of 45 minutes", statement: "A match lasts two equal halves of 45 minutes, which may be shortened only if the referee and both teams agree before kick-off and competition rules allow it. The half-time interval may not exceed 15 minutes, and the referee adds time in each half for time lost.", aliases: ["how long", "duration", "90 minutes", "45 minutes", "half-time", "halftime", "length of a match", "added time", "stoppage time"] }),
  football({ _id: "tg-claim-fb-second-yellow", sourceId: "tg-source-fb-law12", predicate: "second yellow card in a match", value: "sent off", statement: "A player, substitute, or substituted player who receives a second caution (yellow card) in the same match is sent off and shown a red card.", aliases: ["second yellow", "two yellow cards", "2 yellow cards", "second caution", "sent off"] }),
  football({ _id: "tg-claim-fb-goal-size", sourceId: "tg-source-fb-law1", predicate: "size of the goal", value: "7.32 m wide, 2.44 m high", statement: "The goal is 7.32 m (8 yards) wide between the inside of the posts, and the lower edge of the crossbar is 2.44 m (8 feet) above the ground.", aliases: ["goal size", "size of the goal", "how big is the goal", "how wide is the goal", "crossbar", "goalposts"] }),
  football({ _id: "tg-claim-fb-field-size", sourceId: "tg-source-fb-law1", predicate: "size of the pitch", value: "90-120 m long, 45-90 m wide", statement: "The touchline must be 90-120 m long and the goal line 45-90 m, with the touchline longer than the goal line. International matches use tighter limits: 100-110 m by 64-75 m.", aliases: ["pitch size", "field size", "size of the pitch", "how big is the pitch", "how long is the pitch", "dimensions"] }),
  football({ _id: "tg-claim-fb-kick-off-goal", sourceId: "tg-source-fb-law8", predicate: "scoring directly from a kick-off", value: "allowed against the opponents", statement: "A goal may be scored directly against the opponents from the kick-off; if the ball goes straight into the kicker's own goal, the opponents get a corner kick.", aliases: ["kick-off", "kick off", "kickoff", "score from the kick-off"] }),
  football({ _id: "tg-claim-fb-dropped-ball", sourceId: "tg-source-fb-ifab-2025", predicate: "who gets a dropped ball", value: "the team that had or would have gained possession", statement: "Since the 2025/26 Laws of the Game (1 July 2025), when play is stopped with the ball outside the penalty area, the ball is dropped for the team that had or would have gained possession if that is clear to the referee; otherwise it goes to the team that last touched it.", aliases: ["dropped ball", "drop ball", "drop-ball", "restart after injury"], effectiveFrom: "2025-07-01" }),
  football({ _id: "tg-claim-fb-goal-scored", sourceId: "tg-source-fb-law10", predicate: "when a goal counts", value: "the whole ball crosses the goal line", statement: "A goal is scored only when the whole of the ball passes over the goal line between the posts and under the crossbar, provided the scoring team has committed no offence.", aliases: ["whole ball", "goal line", "is it a goal", "crossed the line", "goal counts"] }),
  football({ _id: "tg-claim-fb-drawn-match", sourceId: "tg-source-fb-law10", predicate: "deciding a drawn match", value: "away goals, extra time, or penalties", statement: "When competition rules require a winner after a draw, the only permitted methods are the away goals rule, two equal periods of extra time of no more than 15 minutes each, and a penalty shoot-out, alone or combined.", aliases: ["draw", "drawn", "tie", "extra time", "penalty shoot-out", "shootout", "away goals"] }),
  football({ _id: "tg-claim-fb-free-kick-distance", sourceId: "tg-source-fb-law13", predicate: "distance of opponents at a free kick", value: "9.15 m (10 yards)", statement: "Until a free kick is in play, opponents must be at least 9.15 m (10 yards) from the ball, unless they stand on their own goal line between the posts.", aliases: ["free kick", "wall", "9.15", "10 yards", "distance"] }),
  football({ _id: "tg-claim-fb-free-kick-direct", sourceId: "tg-source-fb-law13", predicate: "scoring directly from a free kick", value: "direct yes, indirect no", statement: "A direct free kick kicked straight into the opponents' goal is a goal. An indirect free kick that goes straight in is not a goal; play restarts with a goal kick.", aliases: ["free kick", "indirect free kick", "direct free kick", "score directly"] }),
  football({ _id: "tg-claim-fb-penalty-procedure", sourceId: "tg-source-fb-law14", predicate: "how a penalty kick is taken", value: "keeper on the goal line, ball kicked forward", statement: "At a penalty kick the defending goalkeeper must stay on the goal line between the posts, facing the kicker, until the ball is kicked. The kicker must kick the ball forward; a backheel is allowed if the ball moves forward.", aliases: ["penalty", "penalty kick", "spot kick", "goal line", "backheel"] }),
  football({ _id: "tg-claim-fb-penalty-keeper-offence", sourceId: "tg-source-fb-law14", predicate: "goalkeeper offence at a penalty", value: "goal stands, or retake if the keeper stops it", statement: "If the goalkeeper commits an offence at a penalty kick and the ball still goes in, the goal stands; if the goalkeeper's action stops the ball going in, the kick is retaken.", aliases: ["penalty", "goalkeeper off the line", "keeper off the line", "retake", "retaken"] }),
  football({ _id: "tg-claim-fb-throw-in-technique", sourceId: "tg-source-fb-law15", predicate: "how to take a throw-in", value: "both hands, from behind and over the head", statement: "The thrower must face the field, have part of each foot on or behind the touchline, and throw the ball with both hands from behind and over the head, from where the ball left the field.", aliases: ["throw-in", "throw in", "foul throw", "both hands"] }),
  football({ _id: "tg-claim-fb-throw-in-goal", sourceId: "tg-source-fb-law15", predicate: "scoring directly from a throw-in", value: "not allowed", statement: "A goal cannot be scored directly from a throw-in; if the ball goes straight into the opponents' goal, a goal kick is awarded.", aliases: ["throw-in", "throw in", "score from a throw", "score directly"] }),
  football({ _id: "tg-claim-fb-handball-scorer", sourceId: "tg-source-fb-law12", predicate: "goal after the ball touches the scorer's hand or arm", value: "not allowed, even if accidental", statement: "A goal does not count if the scorer scores directly from their hand or arm, or immediately after the ball has touched their hand or arm, even if the touch was accidental.", aliases: ["handball", "hand ball", "hand", "arm", "accidental handball"] }),
];

export const cricketBaseId = "tg-kb-cricket-laws";
export const cricketKnowledgeBase: KnowledgeBase = {
  _id: cricketBaseId,
  title: "Cricket rules desk",
  description: "Original summaries of the MCC Laws of Cricket and ICC international playing conditions. Claims record when each rule took effect and whether it applies to club cricket under the Laws or to international matches, which sometimes changed on different dates.",
  kind: "real",
  mcpId: null,
  suggestedQuestions: [
    "Is a bunny-hop boundary catch allowed in club cricket?",
    "How long does a new batter have to be ready in a T20I?",
    "Can bowlers use saliva to shine the ball?",
    "After a batter is caught, who faces the next ball?",
    "How many players are in a Hundred team?",
  ],
  showcase: [
    { title: "New edition of the Laws", question: "Is a bunny-hop boundary catch allowed in club cricket?", asOf: null, lesson: "The 2026 MCC Laws took effect on 1 October 2026: a fielder may touch the ball only once while airborne beyond the rope. The older rule that allowed it applied until 30 September 2026." },
    { title: "Same date, different level", question: "Was a bunny-hop boundary catch allowed in club cricket on 2026-03-01?", asOf: null, lesson: "On 1 March 2026, club cricket still followed the old Law, while international cricket had banned the bunny hop since June 2025. One date, two correct answers, depending on the level." },
    { title: "Depends on the format", question: "How long does a new batter have to be ready?", asOf: null, lesson: "Club cricket under the Laws allows three minutes, Tests and ODIs two, and T20 internationals 90 seconds. TruthGraph asks for the match type instead of guessing." },
    { title: "Rule replaced", question: "After a batter is caught, who faces the next ball?", asOf: null, lesson: "Since October 2022 the new batter always faces, whether or not the batters crossed. Older explanations still describe the crossing rule." },
  ],
};

const mcc = { knowledgeBaseId: cricketBaseId, publisher: "Marylebone Cricket Club (MCC)", authority: "primary" as const, reviewedAt: reviewed };
const icc = { ...mcc, publisher: "International Cricket Council (ICC)" };
export const cricketSources: KnowledgeSource[] = [
  { ...mcc, _id: "tg-source-ck-mcc-2026", title: "MCC announces new edition of Laws from 1 October 2026", url: "https://www.lords.org/lords/news-stories/mcc-announces-new-edition-of-laws-from-1-october-2026", publishedAt: "2026-02-03" },
  { ...mcc, _id: "tg-source-ck-law19", title: "Laws of Cricket – Law 19: Boundaries", url: "https://lawsofcricket.lords.org/laws-of-cricket/the-over-scoring-runs-dead-ball-and-extras/boundaries", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-espn-2025", title: "MCC changes rule to make boundary catching with bunny hops illegal", publisher: "ESPNcricinfo", authority: "secondary", url: "https://www.cricinfo.com/story/mcc-changes-rule-to-make-boundary-catching-with-bunny-hops-illegal-1490045", publishedAt: "2025-06-13" },
  { ...icc, _id: "tg-source-ck-icc-2025", title: "Several changes made to ICC Playing Conditions", url: "https://www.icc-cricket.com/news/several-changes-made-to-icc-playing-conditions", publishedAt: "2025-06-27" },
  { ...mcc, _id: "tg-source-ck-mcc-2022", title: "MCC's new code of Laws for 2022 come into force", url: "https://www.lords.org/lords/news-stories/mcc-announces-new-code-of-laws-from-1-october-2022", publishedAt: "2022-10-01" },
  { ...icc, _id: "tg-source-ck-icc-2022", title: "ICC announces changes to Playing Conditions", url: "https://www.icc-cricket.com/media-releases/icc-announces-changes-to-playing-conditions", publishedAt: "2022-09-20" },
  { ...mcc, _id: "tg-source-ck-timed-out-2023", title: "MCC statement on Timed Out in Men's ICC Cricket World Cup", url: "https://www.lords.org/lords/news-stories/mcc-statement-on-timed-out-in-men-s-cricket-world", publishedAt: "2023-11-10" },
  { ...mcc, _id: "tg-source-ck-law1", title: "Laws of Cricket – Law 1: The Players", url: "https://lawsofcricket.lords.org/laws-of-cricket/setting-up-the-game/law-1-the-players", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law36", title: "Laws of Cricket – Law 36: Leg Before Wicket", url: "https://lawsofcricket.lords.org/laws-of-cricket/appeals-dismissals/leg-before-wicket", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law14", title: "Laws of Cricket – Law 14: The Follow-on", url: "https://lawsofcricket.lords.org/laws-of-cricket/innings-and-results/the-follow-on", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law17", title: "Laws of Cricket – Law 17: The Over", url: "https://lawsofcricket.lords.org/laws-of-cricket/the-over-scoring-runs-dead-ball-and-extras/the-over", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law21", title: "Laws of Cricket – Law 21: No Ball", url: "https://lawsofcricket.lords.org/laws-of-cricket/the-over-scoring-runs-dead-ball-and-extras/no-ball", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law22", title: "Laws of Cricket – Law 22: Wide Ball", url: "https://lawsofcricket.lords.org/laws-of-cricket/the-over-scoring-runs-dead-ball-and-extras/wide-ball", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law25", title: "Laws of Cricket – Law 25: Batter's Innings; Runners", url: "https://lawsofcricket.lords.org/laws-of-cricket/players-substitutes-runners-and-practice/batters-innings-runners", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law28", title: "Laws of Cricket – Law 28: The Fielder", url: "https://lawsofcricket.lords.org/laws-of-cricket/players-substitutes-runners-and-practice/the-fielder", publishedAt: null },
  { ...mcc, _id: "tg-source-ck-law33", title: "Laws of Cricket – Law 33: Caught", url: "https://lawsofcricket.lords.org/laws-of-cricket/appeals-dismissals/caught", publishedAt: null },
];

const cricket = claimsFor(cricketBaseId, "Cricket");
const catchAliases = ["bunny hop", "bunny-hop", "boundary catch", "airborne", "beyond the boundary", "beyond the rope"];
const level = (value: string) => [{ key: "level", value }];
const timedAliases = ["new batter", "incoming batter", "timed out", "be ready", "ready"];
const format = (value: string) => [{ key: "match type", value }];
export const cricketClaims: Claim[] = [
  cricket({ _id: "tg-claim-ck-catch-club-old", sourceId: "tg-source-ck-espn-2025", predicate: "airborne catch beyond the boundary", value: "allowed if the last ground contact before the first touch was inside the boundary", statement: "Under the MCC Laws before the 2026 edition, only a fielder's last contact with the ground before first touching the ball had to be inside the boundary, so a fielder could leap from beyond the rope, touch the ball more than once while airborne, and still take a fair catch.", aliases: catchAliases, conditions: level("club"), effectiveUntil: "2026-10-01" }),
  cricket({ _id: "tg-claim-ck-catch-club-new", sourceId: "tg-source-ck-law19", predicate: "airborne catch beyond the boundary", value: "only one airborne touch allowed from beyond the boundary", statement: "Since the 2026 edition of the MCC Laws took effect on 1 October 2026, a fielder who jumps from beyond the boundary may touch the ball only once while airborne; any later contact with the ground outside the boundary during that delivery scores a boundary. This ends bunny-hop catches in cricket played under the Laws.", aliases: catchAliases, conditions: level("club"), effectiveFrom: "2026-10-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ck-catch-club-old", reason: "The 2026 edition of the MCC Laws rewrote Law 19.5.2 to allow only one airborne touch from beyond the boundary." }] }),
  cricket({ _id: "tg-claim-ck-catch-intl-old", sourceId: "tg-source-ck-icc-2025", predicate: "airborne catch beyond the boundary", value: "allowed, as under the MCC Law", statement: "Until ICC changed its playing conditions in June 2025, international cricket followed the MCC Law on boundary catches, which allowed repeated airborne touches beyond the rope if the last ground contact before the first touch was inside the boundary.", aliases: catchAliases, conditions: level("international"), effectiveUntil: "2025-06-17" }),
  cricket({ _id: "tg-claim-ck-catch-intl-new", sourceId: "tg-source-ck-icc-2025", predicate: "airborne catch beyond the boundary", value: "only one airborne touch allowed from beyond the boundary", statement: "ICC playing conditions introduced the one-airborne-touch boundary-catch rule before the MCC Laws did: from 17 June 2025 in Tests, 2 July 2025 in ODIs, and 10 July 2025 in T20 internationals.", aliases: catchAliases, conditions: level("international"), effectiveFrom: "2025-06-17", relations: [{ kind: "supersedes", targetId: "tg-claim-ck-catch-intl-old", reason: "ICC adopted the new boundary-catch rule in its June 2025 playing conditions, ahead of the MCC Laws." }] }),
  cricket({ _id: "tg-claim-ck-saliva", sourceId: "tg-source-ck-mcc-2022", predicate: "using saliva to shine the ball", value: "banned", statement: "Since 1 October 2022 the MCC Laws and ICC playing conditions both ban saliva on the ball; sweat is the only natural substance allowed, and using saliva is treated like any other unfair change to the ball's condition. The ban made a temporary Covid-era international measure permanent.", aliases: ["saliva", "spit", "shine the ball", "shining the ball", "polish the ball", "sweat"], effectiveFrom: "2022-10-01" }),
  cricket({ _id: "tg-claim-ck-caught-old", sourceId: "tg-source-ck-icc-2022", predicate: "who faces the next ball after a catch", value: "depended on whether the batters crossed", statement: "Before 1 October 2022, if the batters had crossed before a catch was taken, the not-out batter stayed at the striker's end to face the next ball and the new batter went to the non-striker's end.", aliases: ["caught", "caught out", "faces the next ball", "on strike", "crossed"], effectiveUntil: "2022-10-01" }),
  cricket({ _id: "tg-claim-ck-caught-new", sourceId: "tg-source-ck-mcc-2022", predicate: "who faces the next ball after a catch", value: "the new batter faces the next ball", statement: "Since 1 October 2022, when a batter is out caught, the incoming batter goes to the striker's end and faces the next ball whether or not the batters crossed, unless the over has ended.", aliases: ["caught", "caught out", "faces the next ball", "on strike", "crossed"], effectiveFrom: "2022-10-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ck-caught-old", reason: "The 2022 Laws and ICC playing conditions made the new batter face the next ball regardless of crossing." }] }),
  cricket({ _id: "tg-claim-ck-timed-club", sourceId: "tg-source-ck-timed-out-2023", predicate: "time for the incoming batter to be ready", value: "3 minutes", statement: "Under MCC Law 40, an incoming batter must be ready to receive the ball, or for the partner to receive it, within three minutes of the dismissal or retirement, or may be given out timed out on appeal.", aliases: timedAliases, conditions: format("club") }),
  cricket({ _id: "tg-claim-ck-timed-test", sourceId: "tg-source-ck-icc-2022", predicate: "time for the incoming batter to be ready", value: "2 minutes", statement: "Since 1 October 2022, ICC playing conditions require an incoming batter in a Test to be ready to take strike within two minutes, shorter than the three minutes in the MCC Laws.", aliases: timedAliases, conditions: format("Test"), effectiveFrom: "2022-10-01" }),
  cricket({ _id: "tg-claim-ck-timed-odi", sourceId: "tg-source-ck-icc-2022", predicate: "time for the incoming batter to be ready", value: "2 minutes", statement: "Since 1 October 2022, ICC playing conditions require an incoming batter in an ODI to be ready to take strike within two minutes, shorter than the three minutes in the MCC Laws.", aliases: timedAliases, conditions: format("ODI"), effectiveFrom: "2022-10-01" }),
  cricket({ _id: "tg-claim-ck-timed-t20i", sourceId: "tg-source-ck-icc-2022", predicate: "time for the incoming batter to be ready", value: "90 seconds", statement: "In T20 internationals, ICC playing conditions give an incoming batter ninety seconds to be ready to take strike; the 2022 changes kept this threshold.", aliases: timedAliases, conditions: format("T20I") }),
  cricket({ _id: "tg-claim-ck-players", sourceId: "tg-source-ck-law1", predicate: "number of players per side", value: "eleven", statement: "A cricket match is played between two sides of eleven players, one of whom is captain. Sides may agree to play with fewer or more, but no more than eleven may field at any time.", aliases: ["how many players", "players", "eleven", "team size", "side"] }),
  cricket({ _id: "tg-claim-ck-lbw", sourceId: "tg-source-ck-law36", predicate: "leg before wicket (LBW)", value: "out only if every LBW condition applies", statement: "A batter is out LBW only if all of these apply: the delivery is not a no ball; the ball pitches in line between wicket and wicket or on the off side, so a ball pitching outside leg stump cannot be LBW; it hits the batter's person without first touching the bat; the impact is in line, or outside off stump when no genuine shot is offered; and the ball would otherwise have hit the wicket.", aliases: ["lbw", "leg before wicket", "leg before", "pitching outside leg", "outside leg stump"] }),
  cricket({ _id: "tg-claim-ck-laminated-junior", sourceId: "tg-source-ck-mcc-2026", predicate: "laminated bats", value: "junior cricket only", statement: "Before the 2026 edition of the MCC Laws, laminated bats were legal only in junior cricket.", aliases: ["laminated bat", "laminated bats", "type d bat", "bat"], effectiveUntil: "2026-10-01" }),
  cricket({ _id: "tg-claim-ck-laminated-open-age", sourceId: "tg-source-ck-mcc-2026", predicate: "laminated bats", value: "allowed in open-age cricket at lower levels", statement: "Since the 2026 edition of the MCC Laws took effect on 1 October 2026, laminated (Type D) bats are legal in open-age cricket, not only junior cricket, at the lower levels of the game set by each country's governing body.", aliases: ["laminated bat", "laminated bats", "type d bat", "bat"], effectiveFrom: "2026-10-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ck-laminated-junior", reason: "The 2026 edition extended laminated bats from junior cricket to open-age cricket." }] }),
  cricket({ _id: "tg-claim-ck-over", sourceId: "tg-source-ck-law17", predicate: "balls in an over", value: "six valid balls", statement: "The ball is bowled from each end in turn, in overs of six valid balls; wides and no balls do not count as one of the six.", aliases: ["over", "balls in an over", "how many balls", "six balls"] }),
  cricket({ _id: "tg-claim-ck-consecutive-overs", sourceId: "tg-source-ck-law17", predicate: "bowling two overs in a row", value: "not allowed", statement: "A bowler may not bowl two overs in a row, or parts of two consecutive overs, in the same innings.", aliases: ["consecutive overs", "two overs in a row", "back-to-back overs", "same bowler"] }),
  cricket({ _id: "tg-claim-ck-six", sourceId: "tg-source-ck-law19", predicate: "when a hit scores six", value: "off the bat and first landing beyond the boundary", statement: "A six is scored only if the ball was hit by the bat and first lands beyond the boundary without touching the ground inside the field.", aliases: ["six", "sixer", "6 runs", "over the rope"] }),
  cricket({ _id: "tg-claim-ck-four", sourceId: "tg-source-ck-law19", predicate: "when the ball scores four", value: "reaches the boundary after bouncing, or not off the bat", statement: "A four is scored when the ball reaches the boundary after first touching the ground inside the field, or when it crosses the boundary without having been hit by the bat.", aliases: ["four", "boundary four", "4 runs", "bounces over the rope"] }),
  cricket({ _id: "tg-claim-ck-overthrow", sourceId: "tg-source-ck-mcc-2026", predicate: "what counts as an overthrow", value: "only a throw towards the wickets", statement: "Since the 2026 edition of the MCC Laws (1 October 2026), runs for an overthrow apply only when a fielder throws the ball towards the wickets; a ball that crosses the boundary after a fielder's attempt to stop it is a misfield, not an overthrow.", aliases: ["overthrow", "overthrows", "misfield"], effectiveFrom: "2026-10-01" }),
  cricket({ _id: "tg-claim-ck-no-ball", sourceId: "tg-source-ck-law21", predicate: "no ball penalty", value: "one run plus any runs scored", statement: "A no ball gives the batting side one penalty run immediately, in addition to any runs scored from that ball. The bowler's front foot must land with some part of it behind the popping crease, or it is a no ball.", aliases: ["no ball", "no-ball", "noball", "front foot", "overstepping"] }),
  cricket({ _id: "tg-claim-ck-wide", sourceId: "tg-source-ck-law22", predicate: "wide ball penalty", value: "one run", statement: "A wide gives the batting side one penalty run immediately, in addition to any other runs, and the ball does not count as one of the over.", aliases: ["wide", "wide ball", "wides"] }),
  cricket({ _id: "tg-claim-ck-caught", sourceId: "tg-source-ck-law33", predicate: "out caught", value: "a fair catch off the bat before the ball touches the ground", statement: "A batter is out caught when a fair delivery, not a no ball, touches the bat and is then held by a fielder before it touches the ground.", aliases: ["out caught", "how is a catch", "fair catch", "catch"] }),
  cricket({ _id: "tg-claim-ck-follow-on", sourceId: "tg-source-ck-law14", predicate: "follow-on", value: "200 runs in a 5-day match", statement: "In a two-innings match, the side batting first can make the other side follow on if it leads by at least 200 runs in a match of five days or more, 150 in a three- or four-day match, 100 in a two-day match, or 75 in a one-day match.", aliases: ["follow-on", "follow on", "enforce the follow-on"] }),
  cricket({ _id: "tg-claim-ck-retirement", sourceId: "tg-source-ck-law25", predicate: "retiring during an innings", value: "retired not out if hurt; retired out otherwise unless allowed back", statement: "A batter who retires through illness, injury, or another unavoidable cause may resume and is otherwise recorded as retired not out. A batter who retires for any other reason may return only with the opposing captain's consent, and is otherwise recorded as retired out.", aliases: ["retired out", "retired hurt", "retire", "retired not out"] }),
  cricket({ _id: "tg-claim-ck-helmet", sourceId: "tg-source-ck-law28", predicate: "ball hitting a fielder's helmet on the ground", value: "5 penalty runs and dead ball", statement: "If the ball in play hits a fielding side's helmet lying on the ground, the ball becomes dead and the batting side is awarded 5 penalty runs.", aliases: ["helmet", "penalty runs", "5 runs", "five runs"] }),
  cricket({ _id: "tg-claim-ck-last-over", sourceId: "tg-source-ck-mcc-2026", predicate: "wicket in the last over of the day", value: "the over is completed", statement: "Since the 2026 edition of the MCC Laws (1 October 2026), if a wicket falls in the final over of a day in multi-day cricket after the time for close of play, the over is bowled in full instead of stumps being drawn.", aliases: ["last over", "close of play", "stumps", "end of the day"], effectiveFrom: "2026-10-01" }),
];

export const chessBaseId = "tg-kb-chess-laws";
export const chessKnowledgeBase: KnowledgeBase = {
  _id: chessBaseId,
  title: "Chess rules desk",
  description: "Original summaries of the FIDE Laws of Chess across the 2009, 2014, 2018, and 2023 editions. FIDE applies each edition to competitions that start in its window, and many rules differ between standard, rapid, and blitz games, so claims carry dates and time-control conditions.",
  kind: "real",
  mcpId: null,
  suggestedQuestions: [
    "Can I keep my switched-off phone in my pocket during a game?",
    "What happens after an illegal move in blitz?",
    "How much extra time does the opponent get after an illegal move in rapid chess?",
    "Is a game drawn automatically when the same position appears three times?",
    "What is the touch-move rule?",
    "How many points is a knight worth?",
  ],
  showcase: [
    { title: "Stricter today", question: "Can I keep my switched-off phone in my pocket during a game?", asOf: null, lesson: "Since 2017, any device not approved by the arbiter is forbidden in the playing venue, even when switched off; only event regulations can relax this. Many players still remember the older rule." },
    { title: "Older tournament", question: "Can I keep my switched-off phone in my pocket during a game?", asOf: "2012-05-01", lesson: "For a 2012 tournament, the 2009 Laws applied: a phone was allowed if completely switched off, and you lost only if it made a sound. The date picks the edition." },
    { title: "Depends on time control", question: "What happens after an illegal move?", asOf: null, lesson: "The penalty depends on whether the game is standard, rapid, or blitz, so TruthGraph asks. Add \"in blitz\" to resolve it." },
    { title: "Changed in 2023", question: "How much extra time does the opponent get after an illegal move in rapid chess?", asOf: null, lesson: "The 2023 Laws cut the rapid penalty from two minutes to one. A guide written for 2018 to 2022 events gives the old number." },
    { title: "Surprising change", question: "If I resign when my opponent cannot possibly checkmate me, who wins?", asOf: null, lesson: "Since 2023, such a resignation is a draw, not a loss. Keyword search finds \"resigns\" and returns the old rule that the opponent wins." },
  ],
};

const fide = { knowledgeBaseId: chessBaseId, publisher: "FIDE (International Chess Federation)", authority: "primary" as const, reviewedAt: reviewed, publishedAt: null };
export const chessSources: KnowledgeSource[] = [
  { ...fide, _id: "tg-source-ch-laws-2023", title: "FIDE Laws of Chess, applied from 1 January 2023", url: "https://handbook.fide.com/chapter/E012023" },
  { ...fide, _id: "tg-source-ch-laws-2018", title: "FIDE Laws of Chess, for competitions from 1 January 2018 to 31 December 2022", url: "https://handbook.fide.com/chapter/E012018" },
  { ...fide, _id: "tg-source-ch-laws-2014", title: "FIDE Laws of Chess, for competitions from 1 July 2014 to 30 June 2017", url: "https://handbook.fide.com/chapter/E012014" },
  { ...fide, _id: "tg-source-ch-laws-2009", title: "FIDE Laws of Chess, in force from 1 July 2009", url: "https://handbook.fide.com/chapter/E01pre2014" },
  { ...fide, _id: "tg-source-ch-news-2023", title: "2023 FIDE Laws of Chess published", url: "https://www.fide.com/2023-fide-laws-of-chess-published/", publishedAt: "2023-01-04" },
];

const chess = claimsFor(chessBaseId, "Chess");
const timeControl = (value: string) => [{ key: "time control", value }];
const illegalAliases = ["illegal move", "illegal moves", "second illegal move", "wrong move"];
const penaltyAliases = ["extra time", "extra minutes", "time penalty", "how much time"];
const phoneAliases = ["phone", "mobile phone", "smartphone", "switched off", "switched-off", "electronic device", "pocket"];
const illegalFast = (control: string, id: string, edition: "2014" | "2018") => edition === "2014"
  ? chess({ _id: id, sourceId: "tg-source-ch-laws-2014", predicate: "penalty for an illegal move", value: "loss on the first illegal move", statement: `In ${control} games at competitions starting from 1 July 2014 until the 2018 Laws, a completed illegal move lost the game if the arbiter saw it or the opponent claimed it before making their next move.`, aliases: illegalAliases, conditions: timeControl(control), effectiveFrom: "2014-07-01", effectiveUntil: "2018-01-01" })
  : chess({ _id: id, sourceId: "tg-source-ch-laws-2018", predicate: "penalty for an illegal move", value: "loss on the second illegal move", statement: `Since the 2018 Laws, an illegal move in ${control} no longer loses at once: the arbiter applies the standard penalty, so the first illegal move gives the opponent extra time and the second loses, provided it is noticed before the opponent's next move.`, aliases: illegalAliases, conditions: timeControl(control), effectiveFrom: "2018-01-01", relations: [{ kind: "supersedes", targetId: `tg-claim-ch-illegal-${control}-2014`, reason: `The 2018 Laws replaced the immediate loss for an illegal move in ${control} with the standard two-step penalty.` }] });
export const chessClaims: Claim[] = [
  chess({ _id: "tg-claim-ch-illegal-standard-2009", sourceId: "tg-source-ch-laws-2009", predicate: "penalty for an illegal move", value: "loss on the third illegal move", statement: "Under the 2009 Laws of Chess, in standard games the opponent received two extra minutes for each of a player's first two illegal moves, and a third illegal move lost the game.", aliases: illegalAliases, conditions: timeControl("standard"), effectiveFrom: "2009-07-01", effectiveUntil: "2014-07-01" }),
  chess({ _id: "tg-claim-ch-illegal-standard", sourceId: "tg-source-ch-laws-2023", predicate: "penalty for an illegal move", value: "loss on the second illegal move", statement: "In standard games under the current Laws (the same wording since 2017), a player's first completed illegal move gives the opponent two extra minutes, and the second loses the game, unless the opponent could not checkmate by any legal moves, in which case it is a draw.", aliases: illegalAliases, conditions: timeControl("standard"), effectiveFrom: "2017-07-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ch-illegal-standard-2009", reason: "Later editions reduced the number of illegal moves allowed before a loss from three to two." }] }),
  illegalFast("rapid", "tg-claim-ch-illegal-rapid-2014", "2014"),
  illegalFast("blitz", "tg-claim-ch-illegal-blitz-2014", "2014"),
  illegalFast("rapid", "tg-claim-ch-illegal-rapid", "2018"),
  illegalFast("blitz", "tg-claim-ch-illegal-blitz", "2018"),
  chess({ _id: "tg-claim-ch-penalty-standard", sourceId: "tg-source-ch-laws-2023", predicate: "extra time for the opponent after an illegal move", value: "two minutes", statement: "In standard games, the arbiter adds two minutes to the opponent's clock for a player's first completed illegal move.", aliases: [...penaltyAliases, "illegal move"], conditions: timeControl("standard"), effectiveFrom: "2017-07-01" }),
  chess({ _id: "tg-claim-ch-penalty-rapid-two", sourceId: "tg-source-ch-news-2023", predicate: "extra time for the opponent after an illegal move", value: "two minutes", statement: "For rapid competitions under the 2018 Laws (through 31 December 2022), the illegal-move time penalty was the standard two minutes.", aliases: [...penaltyAliases, "illegal move"], conditions: timeControl("rapid"), effectiveFrom: "2018-01-01", effectiveUntil: "2023-01-01" }),
  chess({ _id: "tg-claim-ch-penalty-rapid-one", sourceId: "tg-source-ch-laws-2023", predicate: "extra time for the opponent after an illegal move", value: "one minute", statement: "Since the 2023 Laws of Chess (applied from 1 January 2023), time penalties in rapid games, including the extra time given after an illegal move, are one minute instead of two. FIDE described this as the main change of the 2023 edition.", aliases: [...penaltyAliases, "illegal move"], conditions: timeControl("rapid"), effectiveFrom: "2023-01-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ch-penalty-rapid-two", reason: "The 2023 Laws reduced rapid time penalties from two minutes to one." }] }),
  chess({ _id: "tg-claim-ch-penalty-blitz", sourceId: "tg-source-ch-laws-2018", predicate: "extra time for the opponent after an illegal move", value: "one minute", statement: "In blitz games, the time penalties in the Laws are one minute instead of two, including the extra time given to the opponent after an illegal move.", aliases: [...penaltyAliases, "illegal move"], conditions: timeControl("blitz"), effectiveFrom: "2018-01-01" }),
  chess({ _id: "tg-claim-ch-threefold", sourceId: "tg-source-ch-laws-2023", predicate: "draw by threefold repetition or the 50-move rule", value: "only on a correct claim by the player to move", statement: "A threefold repetition of the same position, or 50 moves by each side without a capture or pawn move, does not end the game by itself; it is drawn only when the player whose turn it is makes a correct claim.", aliases: ["threefold", "three times", "repetition", "repeated position", "50-move", "50 moves", "fifty moves"] }),
  chess({ _id: "tg-claim-ch-fivefold", sourceId: "tg-source-ch-laws-2023", predicate: "automatic draw by repetition or move count", value: "automatic after a fivefold repetition or 75 moves", statement: "Since the 2014 Laws of Chess, the game is drawn automatically, with no claim needed, when the same position has appeared at least five times or 75 moves have been made by each player without a capture or pawn move; a checkmate on the last move takes precedence.", aliases: ["fivefold", "five times", "75 moves", "75-move", "automatic draw", "automatically", "repetition", "repeated position"], effectiveFrom: "2014-07-01" }),
  chess({ _id: "tg-claim-ch-phone-2009", sourceId: "tg-source-ch-laws-2009", predicate: "mobile phone in the playing venue", value: "allowed if completely switched off", statement: "Under the 2009 Laws of Chess, players could bring a mobile phone into the playing venue if it was completely switched off; the player lost the game only if the device made a sound.", aliases: phoneAliases, effectiveFrom: "2009-07-01", effectiveUntil: "2014-07-01" }),
  chess({ _id: "tg-claim-ch-phone-2014", sourceId: "tg-source-ch-laws-2014", predicate: "mobile phone in the playing venue", value: "forbidden; bringing one loses the game", statement: "Under the 2014 Laws of Chess, a player could not have a mobile phone in the playing venue at all; if it was evident that a player had brought one, the game was lost, unless the competition rules set a lighter penalty.", aliases: phoneAliases, effectiveFrom: "2014-07-01", effectiveUntil: "2017-07-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ch-phone-2009", reason: "The 2014 Laws banned phones in the playing venue even when switched off." }] }),
  chess({ _id: "tg-claim-ch-phone-current", sourceId: "tg-source-ch-laws-2023", predicate: "mobile phone in the playing venue", value: "forbidden unless approved by the arbiter", statement: "Under the current Laws of Chess (the same rule since 2017), a player may not have any electronic device not approved by the arbiter in the playing venue during a game, even switched off. Event regulations may allow devices stored switched off in a bag, or set a less severe penalty.", aliases: phoneAliases, effectiveFrom: "2017-07-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ch-phone-2014", reason: "The 2017 Laws extended the rule to any unapproved electronic device and let event regulations set storage options or penalties." }] }),
  chess({ _id: "tg-claim-ch-resign-2018", sourceId: "tg-source-ch-laws-2018", predicate: "resigning when the opponent cannot checkmate", value: "a win for the opponent", statement: "Under the 2018 Laws of Chess, a game was won by the player whose opponent resigned, with no exception for positions where checkmate was impossible.", aliases: ["resign", "resigns", "resignation", "cannot checkmate", "cannot possibly checkmate"], effectiveUntil: "2023-01-01" }),
  chess({ _id: "tg-claim-ch-resign-2023", sourceId: "tg-source-ch-laws-2023", predicate: "resigning when the opponent cannot checkmate", value: "a draw", statement: "Since the 2023 Laws of Chess, a resignation is scored as a draw, not a loss, if the opponent could not checkmate the resigning player's king by any series of legal moves.", aliases: ["resign", "resigns", "resignation", "cannot checkmate", "cannot possibly checkmate"], effectiveFrom: "2023-01-01", relations: [{ kind: "supersedes", targetId: "tg-claim-ch-resign-2018", reason: "The 2023 Laws added the exception that a resignation is a draw when the opponent cannot checkmate." }] }),
  chess({ _id: "tg-claim-ch-touch-move", sourceId: "tg-source-ch-laws-2023", predicate: "touch-move rule", value: "move the first touched piece that can legally move", statement: "A player who, on their turn, touches one of their own pieces intending to move it must move the first touched piece that can legally move. Touching the king and then a rook means castling on that side if legal; deliberately touching the rook first rules out castling on that side that move.", aliases: ["touch move", "touch-move", "touched", "touches a piece", "castle", "castling"], effectiveFrom: "2014-07-01" }),
  chess({ _id: "tg-claim-ch-players", sourceId: "tg-source-ch-laws-2023", predicate: "number of players", value: "two", statement: "The game of chess is played between two opponents, who move their pieces on an 8 x 8 board of 64 squares; each side starts with 16 pieces, and White moves first.", aliases: ["how many players", "players", "three players", "two players", "opponents", "who moves first", "pieces"] }),
  chess({ _id: "tg-claim-ch-checkmate", sourceId: "tg-source-ch-laws-2023", predicate: "checkmate", value: "the checkmating player wins", statement: "A player wins by checkmating the opponent's king: placing it under attack so that the opponent has no legal move. Checkmate immediately ends the game.", aliases: ["checkmate", "check mate", "mate", "how do you win", "win the game"] }),
  chess({ _id: "tg-claim-ch-stalemate", sourceId: "tg-source-ch-laws-2023", predicate: "stalemate", value: "draw", statement: "If the player to move has no legal move and their king is not in check, the game ends immediately in stalemate, which is a draw. A position where neither player can checkmate by any series of legal moves is also a draw.", aliases: ["stalemate", "no legal move", "dead position"] }),
  chess({ _id: "tg-claim-ch-promotion", sourceId: "tg-source-ch-laws-2023", predicate: "pawn promotion", value: "queen, rook, bishop, or knight", statement: "A pawn that reaches the far rank must be exchanged, as part of the same move, for a queen, rook, bishop, or knight of the same colour. The choice is not limited to pieces already captured, and the new piece acts immediately.", aliases: ["promotion", "promote", "pawn reaches", "last rank", "two queens", "queen"] }),
  chess({ _id: "tg-claim-ch-en-passant", sourceId: "tg-source-ch-laws-2023", predicate: "en passant", value: "only on the very next move", statement: "When a pawn advances two squares from its starting square and lands beside an opponent's pawn, that pawn may capture it as if it had moved only one square. This en passant capture is legal only on the move immediately after the two-square advance.", aliases: ["en passant", "en-passant", "capture a pawn"] }),
  chess({ _id: "tg-claim-ch-castling", sourceId: "tg-source-ch-laws-2023", predicate: "when castling is allowed", value: "only if neither king nor rook has moved and no square is attacked or blocked", statement: "Castling is lost for good once the king has moved, or for a rook that has moved. It is temporarily prevented if the king's square, the square it crosses, or the square it lands on is attacked, or if any piece stands between the king and the rook.", aliases: ["castling", "castle", "can i castle", "in check"] }),
  chess({ _id: "tg-claim-ch-scoring", sourceId: "tg-source-ch-laws-2023", predicate: "points for a win, draw, or loss", value: "1, ½, and 0", statement: "Unless the event's regulations say otherwise, a win scores one point, a draw half a point, and a loss zero.", aliases: ["points", "score", "scoring", "half a point", "how many points"] }),
  chess({ _id: "tg-claim-ch-time-controls", sourceId: "tg-source-ch-laws-2023", predicate: "what counts as rapid or blitz", value: "rapid over 10 and under 60 minutes; blitz 10 minutes or less", statement: "A game is rapid when each player's time, plus 60 times any per-move increment, is more than 10 but less than 60 minutes; it is blitz when that total is 10 minutes or less.", aliases: ["rapid", "blitz", "what is rapid", "what is blitz", "time control", "minutes"] }),
  chess({ _id: "tg-claim-ch-adjust", sourceId: "tg-source-ch-laws-2023", predicate: "adjusting a piece without moving it", value: "say 'I adjust' first, on your own move", statement: "Only the player whose move it is may adjust pieces on their squares, and must first say so, for example 'j'adoube' or 'I adjust'. Any other deliberate contact with a piece counts as intending to move or capture it.", aliases: ["adjust", "j'adoube", "jadoube", "straighten a piece", "fix a piece"] }),
  chess({ _id: "tg-claim-ch-one-hand", sourceId: "tg-source-ch-laws-2023", predicate: "hands used to move and press the clock", value: "one hand, the same hand for the clock", statement: "Each move must be made with one hand only, and the player must press the clock with the same hand that made the move. Using two hands for a single move and pressing the clock is penalised like an illegal move.", aliases: ["one hand", "two hands", "press the clock", "same hand"] }),
  chess({ _id: "tg-claim-ch-late-arrival", sourceId: "tg-source-ch-laws-2023", predicate: "arriving late to a game", value: "loss if after the default time, which is zero unless set", statement: "Event regulations set a default time; if they do not, it is zero. A player who arrives at the board after the default time loses the game unless the arbiter decides otherwise.", aliases: ["late", "arrive late", "default time", "zero tolerance"] }),
  chess({ _id: "tg-claim-ch-colours-reversed", sourceId: "tg-source-ch-laws-2023", predicate: "game started with the wrong colours", value: "replay if fewer than 10 moves, otherwise continue", statement: "If a game started with colours reversed and fewer than 10 moves have been made by both players, it is stopped and replayed with the correct colours; after 10 moves or more, the game continues.", aliases: ["wrong colours", "wrong colors", "colours reversed", "played the wrong colour"] }),
  chess({ _id: "tg-claim-ch-draw-agreement", sourceId: "tg-source-ch-laws-2023", predicate: "agreeing a draw", value: "allowed after both players move, unless event rules restrict it", statement: "Players may agree a draw once both have made at least one move. Event regulations can forbid draw offers or agreements before a set number of moves, or entirely, without the arbiter's consent. A draw offer is made after moving and before pressing the clock, and cannot be withdrawn.", aliases: ["draw offer", "offer a draw", "agree a draw", "agreed draw", "sofia rules"] }),
  chess({ _id: "tg-claim-ch-wrong-draw-claim", sourceId: "tg-source-ch-laws-2023", predicate: "incorrect draw claim", value: "opponent gets two extra minutes", statement: "If a player's claim of a draw by threefold repetition or the 50-move rule is found to be incorrect, the arbiter adds two minutes to the opponent's remaining time and the game continues.", aliases: ["incorrect claim", "wrong claim", "false claim", "draw claim"], conditions: timeControl("standard") }),
  chess({ _id: "tg-claim-ch-incomplete-promotion", sourceId: "tg-source-ch-laws-2023", predicate: "promoting without replacing the pawn", value: "illegal move; the pawn becomes a queen", statement: "If a player moves a pawn to the last rank and presses the clock without replacing it with a new piece, the move is illegal and the pawn is replaced by a queen of the same colour.", aliases: ["promotion", "pawn on the last rank", "forgot to promote", "no queen available"] }),
  chess({ _id: "tg-claim-ch-flag-fall", sourceId: "tg-source-ch-laws-2023", predicate: "running out of time", value: "loss, unless the opponent cannot checkmate", statement: "A player who does not complete the required moves in the allotted time loses the game, but it is a draw if the opponent could not checkmate by any series of legal moves.", aliases: ["out of time", "flag", "flag fall", "time runs out", "lose on time", "timeout"] }),
];
