import { expect, test } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { uploadInvestigationRequestSchema } from "../src/lib/knowledge-import";
import { investigateLocally } from "../src/lib/sample-investigation";
import { realSampleCatalog } from "../src/lib/sample-data";
import { conflictCandidates, documentBudget, indexReviewState, knowledgeBaseSourceQuery } from "../src/lib/curation";

test("requires consent and app access for direct upload AI, with honest provenance", async ({ page }) => {
  const requests: string[] = [];
  const unexpected: string[] = [];
  page.on("request", (request) => { if (request.method() === "POST" && /\/api\/(knowledge-bases|investigate)$/.test(new URL(request.url()).pathname)) unexpected.push(request.url()); });
  await page.route("**/api/investigate-upload", async (route) => {
    const input = uploadInvestigationRequestSchema.parse(route.request().postDataJSON());
    expect(route.request().headers()["x-judge-code"]).toBe("test-only-browser-access-code");
    requests.push(input.request.question);
    const result = investigateLocally(input.request, input.prepared.catalog);
    await route.fulfill({ json: { ...result, mode: "upload", trace: [{ stage: "Direct upload AI", detail: "Browser test response; the provider is mocked. No Sanity or MCP call was made." }, ...result.trace] } });
  });
  await page.goto("/");
  await expect(page.getByText("Live / Sanity Context", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Or paste text", exact: true }).click();
  await page.getByLabel("Document text", { exact: true }).fill("The repair club opens at 09:15 on Sundays. Monthly membership costs 27 euros.");
  await page.getByRole("button", { name: "Review import", exact: true }).click();
  await expect(page.getByRole("radio", { name: "Private browser collection", exact: true })).toBeChecked();
  await page.getByRole("checkbox", { name: "I reviewed the content and have permission to import it." }).check();
  await page.getByRole("button", { name: "Save locally", exact: true }).click();
  await page.getByLabel("Your question", { exact: true }).fill("What is the monthly membership cost?");
  const investigate = page.locator(".tg-composer").getByRole("button", { name: "Investigate", exact: true });
  await expect(investigate).toBeEnabled();
  await page.getByRole("button", { name: "AI on this upload", exact: true }).click();
  await expect(investigate).toBeDisabled();
  await page.getByLabel("Access code", { exact: true }).fill("test-only-browser-access-code");
  await expect(investigate).toBeDisabled();
  expect(requests).toEqual([]);
  await page.getByRole("checkbox", { name: /Send this collection's content/ }).check();
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await investigate.click();
  await expect(page.locator(".tg-answer")).toContainText("27 euros");
  await expect(page.locator(".tg-answer .tg-eyebrow")).toHaveText("ANSWER / DIRECT UPLOAD AI");
  expect(requests).toHaveLength(1);
  await page.unroute("**/api/investigate-upload");
  await page.route("**/api/investigate-upload", (route) => route.fulfill({ status: 503, json: { title: "The model provider is unavailable." } }));
  await page.getByLabel("Your question", { exact: true }).fill("What time does the club open?");
  await investigate.click();
  await expect(page.locator(".tg-error").filter({ hasText: "The model provider is unavailable." })).toBeVisible();
  await expect(page.getByText("The question or context changed.", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Private preview", exact: true }).click();
  await expect(page.locator(".tg-answer")).toHaveCount(0);
  await investigate.click();
  await expect(page.locator(".tg-answer")).toContainText("09:15");
  await expect(page.locator(".tg-answer .tg-eyebrow")).toHaveText("ANSWER / LOCAL EVIDENCE");
  expect(await page.evaluate(() => localStorage.getItem("truthgraph-imports-v1"))).not.toContain("test-only-browser-access-code");
  expect(unexpected).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test("curates conflicting claims, edits and deletes with confirmation, and records an index review", async ({ page }, testInfo) => {
  const catalog = structuredClone(realSampleCatalog({ includeLocalSamples: true }));
  const base = catalog.knowledgeBases.find((candidate) => candidate._id === "tg-kb-framework-notes")!;
  base.mcpId = "kbtest";
  let revision = 1;
  const code = "browser-test-only-management-code";
  const actions: string[] = [];
  const overview = () => ({
    revision: `base-${revision}`, budget: documentBudget(catalog), indexState: indexReviewState(base), sourceQuery: knowledgeBaseSourceQuery(base._id),
    knowledgeBase: base, sources: catalog.sources, claims: catalog.claims.map((claim) => ({ ...claim, revision: `claim-${revision}` })),
    conflicts: conflictCandidates(catalog, base._id), decisions: catalog.claims.flatMap((claim) => claim.relations.map((relation, index) => ({ ...relation, claimId: claim._id, _key: `relation-${index}` }))),
  });
  await page.route("**/api/knowledge-bases", (route) => route.fulfill({ json: { knowledgeBases: catalog.knowledgeBases, budget: documentBudget(catalog) } }));
  await page.route("**/api/admin**", async (route) => {
    if (route.request().headers()["x-knowledge-admin-code"] !== code) return route.fulfill({ status: 401, json: { title: "A valid knowledge-management code is required." } });
    if (route.request().method() === "GET") return route.fulfill({ json: overview() });
    const body = route.request().postDataJSON();
    expect(body.expectedRevision).toBe(`base-${revision}`);
    expect(body.knowledgeBaseId).toBe(base._id);
    actions.push(body.action);
    if (body.action === "add-relation") catalog.claims.find((claim) => claim._id === body.fromId)!.relations.push({ kind: body.kind, targetId: body.toId, reason: body.reason });
    if (body.action === "remove-relation") catalog.claims.find((claim) => claim._id === body.claimId)!.relations.splice(Number(body.key.split("-").at(-1)), 1);
    if (body.action === "update-claim") Object.assign(catalog.claims.find((claim) => claim._id === body.claimId)!, { statement: body.statement, value: body.value, effectiveFrom: body.effectiveFrom, effectiveUntil: body.effectiveUntil });
    if (body.action === "delete-claim") catalog.claims = catalog.claims.filter((claim) => claim._id !== body.claimId);
    if (body.action === "confirm-index") base.indexReviewedAt = "2026-10-01T12:01:00.000Z";
    else base.contentChangedAt = "2026-10-01T12:00:00.000Z";
    revision++;
    return route.fulfill({ json: { message: "Test change confirmed." } });
  });
  await page.goto("/");
  await page.getByRole("button", { name: "Knowledge bases", exact: true }).click();
  await page.getByRole("button", { name: "Refresh knowledge bases", exact: true }).click();
  await page.getByLabel("Knowledge base", { exact: true }).selectOption(base._id);
  await page.getByRole("button", { name: "Curate", exact: true }).click();
  await page.getByLabel("Knowledge admin code", { exact: true }).fill("incorrect-test-code");
  await page.getByRole("button", { name: "Open curation", exact: true }).click();
  await expect(page.locator(".tg-curate").getByRole("alert")).toContainText("valid knowledge-management code");
  await page.getByLabel("Knowledge admin code", { exact: true }).fill(code);
  await page.getByRole("button", { name: "Open curation", exact: true }).click();
  const conflict = page.locator(".tg-curate-conflict");
  await expect(conflict).toHaveCount(1);
  await conflict.getByRole("textbox", { name: "Reason, shown to every future reader" }).fill("The official release page explicitly applies the new annual policy from Node.js 27.");
  await conflict.getByRole("button", { name: "Record decision", exact: true }).click();
  await expect(conflict).toHaveCount(0);
  const decisions = page.locator(".tg-curate-decision").filter({ hasText: "new annual policy" });
  await decisions.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(conflict).toHaveCount(1);
  await page.getByRole("searchbox", { name: "Search claims", exact: true }).fill("tg-claim-lint-16");
  let record = page.locator(".tg-curate .tg-library-record");
  await record.locator("summary").click();
  await record.getByLabel("Value", { exact: true }).fill("removed; run ESLint directly");
  await record.getByRole("button", { name: "Save changes", exact: true }).click();
  await expect(record).toContainText("removed; run ESLint directly");
  await record.locator("summary").click();
  await record.getByRole("button", { name: "Delete", exact: true }).click();
  expect(actions).not.toContain("delete-claim");
  await record.getByRole("button", { name: "Keep", exact: true }).click();
  await record.getByRole("button", { name: "Delete", exact: true }).click();
  await record.getByRole("button", { name: "Confirm delete", exact: true }).click();
  record = page.locator(".tg-curate .tg-library-record");
  await expect(record).toHaveCount(0);
  await page.getByRole("checkbox", { name: /I checked the current entries/ }).check();
  await page.getByRole("button", { name: "Record index review", exact: true }).click();
  await expect(page.getByRole("region", { name: "Index review" })).toContainText("Operator confirmed");
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("curation.png"), fullPage: true });
  expect(actions).toEqual(["add-relation", "remove-relation", "update-claim", "delete-claim", "confirm-index"]);
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain(code);
});

test("publishes a live snapshot only after explicit consent", async ({ page }, testInfo) => {
  const catalog = realSampleCatalog({ includeLocalSamples: true });
  const base = { ...catalog.knowledgeBases.find((candidate) => candidate._id === "tg-kb-framework-notes")!, mcpId: "kbtest" };
  const id = "795ef221-0a25-465c-92ee-0da029160063";
  let publications = 0;
  await page.route("**/api/knowledge-bases", (route) => route.fulfill({ json: { knowledgeBases: [base], budget: documentBudget(catalog) } }));
  await page.route("**/api/investigate", (route) => {
    const result = investigateLocally(route.request().postDataJSON(), catalog);
    return route.fulfill({ json: { ...result, mode: "live", shareReceipt: { id, issuedAt: "2026-10-01T12:00:00.000Z", expiresAt: "2026-10-01T13:00:00.000Z", signature: "a".repeat(64) } } });
  });
  await page.route("**/api/investigations", (route) => {
    expect(route.request().postDataJSON().consent).toBe(true);
    publications++;
    return route.fulfill({ status: 201, json: { path: `/investigations/${id}` } });
  });
  await page.goto("/");
  await page.getByRole("button", { name: "Knowledge bases", exact: true }).click();
  await page.getByRole("button", { name: "Refresh knowledge bases", exact: true }).click();
  await page.getByLabel("Knowledge base", { exact: true }).selectOption(base._id);
  await page.getByRole("navigation", { name: "Workspace" }).getByRole("button", { name: "Investigate", exact: true }).click();
  await page.locator(".tg-tour").getByRole("button", { name: /Corrected date/ }).click();
  await expect(page.locator(".tg-answer")).toContainText("September 11, 2023");
  await page.getByRole("button", { name: "Copy share link", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Publish investigation snapshot?" });
  await expect(dialog).toBeVisible();
  expect(publications).toBe(0);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Copy share link", exact: true })).toBeFocused();
  await page.getByRole("button", { name: "Copy share link", exact: true }).click();
  await dialog.getByRole("button", { name: "Publish and copy link", exact: true }).click();
  await expect(dialog.getByRole("link", { name: "Open saved investigation" })).toHaveAttribute("href", new RegExp(`/investigations/${id}$`));
  expect(publications).toBe(1);
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("share-consent.png"), fullPage: true });
});