"use client";

import { ArrowUpRight, BookOpen, FileText, Layers3 } from "lucide-react";
import { type Claim, type KnowledgeBase, type KnowledgeSource } from "@/lib/knowledge";

export function KnowledgeSourceShelf({ base, sources, claims, collections, onSelect, onInspect }: { base?: KnowledgeBase; sources: KnowledgeSource[]; claims: Claim[]; collections: KnowledgeBase[]; onSelect: (id: string) => void; onInspect: (id: string) => void }) {
  return <aside className="tg-source-shelf" aria-label={base ? "Selected sources" : "Available collections"}>
    <div className="tg-shelf-heading"><span className="tg-eyebrow">{base ? "SOURCE MATERIAL" : "COLLECTIONS"}</span><span className="tg-mono">{String(base ? sources.length : collections.length).padStart(2, "0")}</span></div>
    <h2>{base ? "On the record" : "Already on your desk"}</h2>
    {base ? <><p className="tg-shelf-caption">{base.title}</p>{sources.map((source, index) => <article className={`tg-source-card tg-source-color-${index % 3}`} key={source._id}><button type="button" onClick={() => onInspect(source._id)} aria-label={`Inspect evidence from ${source.title}`}><div className="tg-source-cover"><div><span className="tg-mono">{String(index + 1).padStart(2, "0")}</span><span className="tg-source-kind"><FileText size={12} aria-hidden="true" />{source.fileName ? source.fileName.split(".").pop()?.toUpperCase() : "SOURCE"}</span></div><h3>{source.title}</h3><p>{claims.find((claim) => claim.sourceId === source._id)?.statement || source.publisher}</p><span className="tg-source-open"><ArrowUpRight size={16} aria-hidden="true" /></span></div><div className="tg-source-caption"><span>{source.publisher}</span><span>{source.authority}</span></div></button></article>)}{!sources.length && <div className="tg-shelf-empty"><BookOpen size={24} aria-hidden="true" /><p>No source records loaded.</p></div>}<div className="tg-shelf-total"><BookOpen size={14} aria-hidden="true" /><span>{sources.length} sources</span><span>{claims.length} loaded claims</span></div></> : <div className="tg-collection-picker">{collections.map((collection, index) => <button type="button" key={collection._id} onClick={() => onSelect(collection._id)}><span className="tg-collection-index">{String(index + 1).padStart(2, "0")}</span><span><strong>{collection.title}</strong><small>{collection.kind === "synthetic" ? "Synthetic reasoning fixtures" : collection._id.startsWith("tg-upload-") ? "Your imported documents" : "Reference collection"}</small></span><ArrowUpRight size={17} aria-hidden="true" /></button>)}{!collections.length && <div className="tg-shelf-empty"><Layers3 size={24} aria-hidden="true" /><p>No shared collections configured.</p></div>}</div>}
  </aside>;
}