#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
set +x
umask 077
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE="$PWD/.env.local"
[[ -t 0 ]] || { warn "Run this wizard directly in your own terminal."; exit 1; }
[[ ! -L "$ENV_FILE" ]] || { warn "Refusing to overwrite a symlinked environment file."; exit 1; }
node -e 'process.exit(Number(process.versions.node.split(".")[0]) === 24 ? 0 : 1)' || { warn "Activate Node.js 24 before running this wizard."; exit 1; }

capture_secret() {
  local key="$1" prompt="$2" value
  while true; do
    ask_secret "$key" "$prompt"
    value="${!key}"
    if [[ -n "$value" && "$value" != *[[:space:]]* && "$value" != *\#* && "$value" != *\"* && "$value" != *\'* && "$value" != *\\* ]]; then
      write_env "$key" "$value"
      export "$key"
      return
    fi
    warn "Enter a non-empty credential without whitespace, quotes, backslashes, or #. Its value will not be printed."
  done
}

banner "TruthGraph: configure a real evidence corpus"
say "This changes only this project's local environment and the Sanity project you select."
say "No public deployment, Git push, or DEV publication is performed."
confirm "Proceed, keeping local demo mode until the final activation stage?" || exit 0
write_env APP_MODE demo

stage "Create or select the Path One project"
open_url "https://www.sanity.io/manage"
step "Sign in yourself. Create or select a dedicated TruthGraph project."
step "Create a production dataset. Public is appropriate only for this public documentation corpus."
ask SANITY_STUDIO_PROJECT_ID "Project ID:"
[[ "$SANITY_STUDIO_PROJECT_ID" =~ ^[a-z0-9]+$ ]] || { warn "The project ID must contain lowercase letters and digits."; exit 1; }
ask SANITY_STUDIO_DATASET "Dataset name [production]:"
SANITY_STUDIO_DATASET="${SANITY_STUDIO_DATASET:-production}"
[[ "$SANITY_STUDIO_DATASET" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || { warn "Invalid dataset name."; exit 1; }
write_env SANITY_STUDIO_PROJECT_ID "$SANITY_STUDIO_PROJECT_ID"
write_env SANITY_STUDIO_DATASET "$SANITY_STUDIO_DATASET"
export SANITY_STUDIO_PROJECT_ID SANITY_STUDIO_DATASET

stage "Project tokens for the content corpus"
open_url "https://www.sanity.io/manage"
step "Select the chosen project, then API > Tokens. Create an Editor token for seeding."
capture_secret SANITY_WRITE_TOKEN "Project Editor token (hidden):"
step "A private dataset also needs a Viewer token for the app's read-only catalog."
if confirm "Is this dataset private?"; then
  capture_secret SANITY_READ_TOKEN "Project Viewer token (hidden):"
else
  write_env SANITY_READ_TOKEN ""
  export SANITY_READ_TOKEN=""
fi
note "Keep the project write token on a deployment only when authenticated knowledge imports and mapping changes are enabled. Read-only deployments do not need it."

stage "Seed the corpus and deploy its schema"
say "This adds one optional real-source sample: 1 knowledge base, 3 sources, and 10 claims. Synthetic fixtures and legacy records are excluded; existing records are preserved."
confirm "Write the corpus and deploy the schema to the project selected above?" || exit 0
[[ -d node_modules ]] || npm ci
npm run seed
step "Authenticate the Sanity CLI in your own browser for schema deployment."
npx sanity login
npm run sanity:schema
npm run export:kb
note "knowledge-base/truthgraph.md is ready for upload in the next stage."

stage "Build the Knowledge Base and Context MCP"
open_url "https://www.sanity.io/docs/ai/sanity-context-create-knowledge-base"
step "Follow the guide's Dashboard link and enable Context / Knowledge Bases for your organization in Labs."
step "Create a Knowledge Base for your chosen real corpus. Add the tgSource/tgClaim dataset records or upload knowledge-base/truthgraph.md for the optional sample."
step "Purpose: answer questions by determining which source-backed claims apply, retaining relevant alternatives and historical claims."
step "Instruction: preserve claim IDs, exact statements verbatim, source URLs, subjects, predicates, values, version scopes, effective dates, conditions, and relationships."
step "Build the Knowledge Base. Inspect entries and resolve any genuine same-scope conflicts."
step "Copy its platform kb... ID. In Studio (npm run sanity:dev in another terminal), open the matching Knowledge base record and set its Sanity Knowledge Base ID field; publish the record."
open_url "https://www.sanity.io/docs/ai/sanity-context-configure-mcp"
step "Create a Context endpoint for TruthGraph with Knowledge Base sources. Do not add a dataset source. The application scopes each request to the selected kb... ID."
ask SANITY_CONTEXT_MCP_URL "Copy the Context MCP endpoint URL:"
write_env SANITY_CONTEXT_MCP_URL "$SANITY_CONTEXT_MCP_URL"
export SANITY_CONTEXT_MCP_URL
open_url "https://www.sanity.io/manage/org/api/tokens"
step "Select the organization. Create a Context Viewer organization token, not a project token."
capture_secret SANITY_ORGANIZATION_TOKEN "Organization Context Viewer token (hidden):"

stage "Configure the model and judge access"
ask MODEL_PROVIDER "Model provider, openai or google [openai]:"
MODEL_PROVIDER="${MODEL_PROVIDER:-openai}"
[[ "$MODEL_PROVIDER" == openai || "$MODEL_PROVIDER" == google ]] || { warn "Enter openai or google."; exit 1; }
write_env MODEL_PROVIDER "$MODEL_PROVIDER"
export MODEL_PROVIDER
if [[ "$MODEL_PROVIDER" == google ]]; then
  open_url "https://aistudio.google.com/apikey"
  step "Create a Gemini API key in Google AI Studio. Check its quota and billing before enabling public access."
  capture_secret GOOGLE_GENERATIVE_AI_API_KEY "Gemini API key (hidden):"
  MODEL_VARIABLE=GOOGLE_MODEL; MODEL_DEFAULT=gemini-3.5-flash-lite
else
  open_url "https://platform.openai.com/api-keys"
  step "Create an API key in your own OpenAI project. API billing is separate from a ChatGPT subscription."
  step "Set a project spending limit before enabling public access."
  capture_secret OPENAI_API_KEY "OpenAI API key (hidden):"
  MODEL_VARIABLE=OPENAI_MODEL; MODEL_DEFAULT=gpt-4.1-mini
fi
ask "$MODEL_VARIABLE" "Model ID [$MODEL_DEFAULT]:"
printf -v "$MODEL_VARIABLE" '%s' "${!MODEL_VARIABLE:-$MODEL_DEFAULT}"
[[ "${!MODEL_VARIABLE}" =~ ^[a-zA-Z0-9._:-]+$ ]] || { warn "Enter a model ID, not a URL or command."; exit 1; }
write_env "$MODEL_VARIABLE" "${!MODEL_VARIABLE}"
export "$MODEL_VARIABLE"
ask_secret LIVE_ACCESS_CODE "Judge access code, 24+ characters (Enter generates a private random code):"
LIVE_ACCESS_CODE="${LIVE_ACCESS_CODE:-$(node -p 'require("node:crypto").randomBytes(24).toString("hex")')}"
[[ ${#LIVE_ACCESS_CODE} -ge 24 && "$LIVE_ACCESS_CODE" =~ ^[a-zA-Z0-9_-]+$ ]] || { warn "Use at least 24 letters, digits, underscores, or hyphens for this code."; exit 1; }
write_env LIVE_ACCESS_CODE "$LIVE_ACCESS_CODE"
export LIVE_ACCESS_CODE
note "The code is stored privately in .env.local. Share only this app code with judges, never an API token."
if confirm "Enable authenticated knowledge uploads and mapping changes in the app?"; then
  ask_secret KNOWLEDGE_ADMIN_CODE "Separate management code, 24+ characters (Enter generates a private random code):"
  KNOWLEDGE_ADMIN_CODE="${KNOWLEDGE_ADMIN_CODE:-$(node -p 'require("node:crypto").randomBytes(24).toString("hex")')}"
  [[ ${#KNOWLEDGE_ADMIN_CODE} -ge 24 && "$KNOWLEDGE_ADMIN_CODE" =~ ^[a-zA-Z0-9_-]+$ && "$KNOWLEDGE_ADMIN_CODE" != "$LIVE_ACCESS_CODE" ]] || { warn "Use a different management code with at least 24 letters, digits, underscores, or hyphens."; exit 1; }
  write_env KNOWLEDGE_ADMIN_CODE "$KNOWLEDGE_ADMIN_CODE"
  export KNOWLEDGE_ADMIN_CODE
  note "Management uses the project write token. Keep both credentials private; judges need only LIVE_ACCESS_CODE."
else
  write_env KNOWLEDGE_ADMIN_CODE ""
  export KNOWLEDGE_ADMIN_CODE=""
  note "In-app imports and mapping changes are disabled. Omit the project write token from a read-only hosted deployment."
fi

stage "Activate the local live application"
ask APP_URL "Application origin [http://localhost:3000]:"
APP_URL="${APP_URL:-http://localhost:3000}"
write_env APP_URL "$APP_URL"
export APP_URL
confirm "Switch this project's local configuration to live mode?" || exit 0
write_env APP_MODE live
export APP_MODE=live
npm run doctor
say "Restart the existing Path One server in its own terminal, then reload the application."
say "If no server is running, start npm run dev in another terminal and use its matching origin."
pause "Press Enter after the live application is running at APP_URL."
open_url "$APP_URL"

stage "Verify the real integration"
npm run check:live
if confirm "Run a model-backed investigation using the selected corpus's suggested question? This consumes API quota."; then
  npm run check:live -- --exercise
else
  SKIPPED+=("Live model acceptance not run. Execute npm run check:live -- --exercise before submission.")
fi
SKIPPED+=("Deploy separately, configure hosted secrets and rate limits, and repeat acceptance against the hosted APP_URL.")
finish
warn "Setup does not publish your challenge entry. Use the real project ID and actual live evidence in your DEV post."
